---
abstract: 'Build an INSTALL file'
author:
  - 'Marcel Grünauer <marcel@cpan.org>'
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::More: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-InstallGuide
no_index:
  directory:
    - corpus
    - inc
    - examples
requires:
  Dist::Zilla::File::FromCode: '0'
  Dist::Zilla::Role::FileGatherer: '0'
  Dist::Zilla::Role::TextTemplate: '0'
  Moose: '0'
  Moose::Autobox: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/doherty/Dist-Zilla-Plugin-InstallGuide/issues
  repository: git://github.com/doherty/Dist-Zilla-Plugin-InstallGuide.git
version: '1.200003'
