---
abstract: 'Build an INSTALL file'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 3.101440, CPAN::Meta::Converter version 2.101410'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-InstallGuide
provides:
  Dist::Zilla::Plugin::InstallGuide:
    file: lib/Dist/Zilla/Plugin/InstallGuide.pm
    version: 1.101460
requires:
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::InstallTool: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  Moose::Autobox: 0
  perl: 5.008
resources:
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-InstallGuide/
  repository: http://github.com/hanekomu/Dist-Zilla-Plugin-InstallGuide
version: 1.101460
